apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-monitor
  namespace: prime
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: api-monitor
  template:
    metadata:
      labels:
        app: api-monitor
    spec:
      containers:
        - name: api-monitor-con
          image: shadow2811/api-monitor:v1.0
          ports:
            - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: api-services
  namespace: prime
spec:
  type: NodePort
  selector:
    app: api-monitor
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
status:
  loadBalancer: {}
